# Generated by Django 3.1.7 on 2021-05-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0002_auto_20210510_0417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='File',
            field=models.FileField(upload_to=''),
        ),
    ]
