# Generated by Django 3.1.7 on 2021-09-17 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0004_download'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('hotel_Main_Img', models.FileField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='download',
        ),
    ]
