# Generated by Django 3.1.7 on 2021-09-18 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0005_auto_20210918_0037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileupload',
            old_name='hotel_Main_Img',
            new_name='file_uploaded',
        ),
        migrations.RemoveField(
            model_name='fileupload',
            name='name',
        ),
    ]
