# Generated by Django 3.1.7 on 2021-09-18 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0006_auto_20210918_0111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='file_uploaded',
        ),
    ]
