# Generated by Django 3.1.7 on 2021-09-18 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0007_remove_fileupload_file_uploaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='file',
            field=models.FileField(default='file', upload_to=''),
        ),
    ]
