# Generated by Django 3.1.7 on 2021-09-18 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0009_remove_fileupload_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='name',
            field=models.FileField(default='file', upload_to=''),
        ),
    ]
