# Generated by Django 3.1.7 on 2021-09-18 00:59

import convert.formatChecker
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0011_auto_20210918_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=convert.formatChecker.ContentTypeRestrictedFileField(default='file', null=True, upload_to='', verbose_name=''),
        ),
    ]
