# Generated by Django 3.1.7 on 2021-09-24 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0013_auto_20210920_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('body', models.TextField()),
            ],
        ),
    ]
