# Generated by Django 3.1.7 on 2021-09-24 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0014_snippet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
